---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ArtifactStore:
    Type: String
  EncryptionKeyAlias:
    Type: String
  Repository:
    Type: String
  SCMOwner:
    Type: String

Resources:
  BuildPublishNpm:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build-publish-npm
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/Deployer
      EncryptionKey: !Ref EncryptionKeyAlias
      Cache:
        Type: NO_CACHE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ARTIFACT_STORE
            Value: !Ref ArtifactStore
      Source:
        BuildSpec: devops/buildspecs/npm.buildspec.yml
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE

  PipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: '{{resolve:secretsmanager:cicd-credentials:SecretString:github_token}}'
      Filters:
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/{Branch}'
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref AWS::StackName
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStore
        EncryptionKey:
          Id: !Ref EncryptionKeyAlias
          Type: KMS
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/Pipeline
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Provider: GitHub
                Owner: ThirdParty
                Version: 1
              OutputArtifacts:
                - Name: SourceCode
              Configuration:
                Owner: !Ref SCMOwner
                Repo: !Ref Repository
                Branch: master
                OAuthToken: '{{resolve:secretsmanager:cicd-credentials:SecretString:github_token}}'
                PollForSourceChanges: false
        - Name: Build_And_Publish
          Actions:
            - Name: Build_Package
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceCode
              Configuration:
                ProjectName: !Ref BuildPublishNpm
                EnvironmentVariables: !Sub '[{"name":"REPOSITORY","value":"${Repository}"},{"name":"SCM_OWNER","value":"${SCMOwner}"}]'
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/Deployer
